---
tenancy: default
vpc_priv_net_cidr: 10.0.0.0/16
vpc_priv_net_public_subnet_cidr: 10.0.0.0/24
vpc_priv_net_priv_subnet_cidr: 10.0.1.0/24
vpc_dmz_cidr: 10.1.0.0/16
vpc_dmz_subnet1_cidr: 10.1.0.0/24
dmz_instance_type: t2.micro
dmz_instance_name: dmz-ssh-tunnel-vm
priv_network_instance_type: t2.micro
priv_network_instance_name: priv-network-vm
transit_gateway_asn: 64514
transit_gateway_auto_associate: true
transit_gateway_auto_propagate: true
transit_gateway_dns_support: true
