---
- name: Create VM Demo
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "vm_blueprints/{{vm_blueprint}}.yml"
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - aws_region is defined
          - aws_keypair_name is defined
          - aws_instance_size is defined
        fail_msg: "Required variables not set"

    - name: Include create vm role
      ansible.builtin.include_role:
        name: create_vm
